% This functions takes in a vector of continuous values generated by some
% continuous distribution, and morphs them into a vector integer values
% with the similar total sum using a simple algorythm of the residual
% accumulation.
% The functions does not shuffle the vector, so it has to be done elsewhere
% if needed. The orientation of the output vector is the same as of the
% input vector
% INPUT:
% - [continuous] - a vector of values, supposedly continuous
% OUTPUT:
% - [integer] - a vector of values, integer.

% Sum of elements in [continuous] and [integer] should be almost similar,
% with difference < 1 (the final residual). If the input vector contains
% only the integer values, it does not change


function integer=cont2int(continuous)
residual=0;
integer(1,1:size(continuous,1))=0;

if (size(continuous,1)==1)&&(size(continuous,2)>=1)
    for f=1:size(continuous,2)
        integer(1,f)=round(continuous(1,f)+residual);
        residual=continuous(1,f)-integer(1,f)+residual;
    end
elseif (size(continuous,1)>1)&&(size(continuous,2)==1)
    continuous=continuous';
    for f=1:size(continuous,2)
        integer(1,f)=round(continuous(1,f)+residual);
        residual=continuous(1,f)-integer(1,f)+residual;
    end
    integer=integer';
elseif (size(continuous,1)<1)||(size(continuous,2)<1)
    integer=continuous;
else
    error('Wrong format of the continuous vector: matrix')
end
if or(residual<-0.50000000000001,residual>0.50000000000000001)
    error(['Final residual is out of range, check the cont2int() function, residual is ' num2str(residual)])
end
end




